/**
 * OpenAI-compatible gateway.
 *
 * The canvas speaks the ordinary image API, so keeping that shape here means
 * the frontend never learns which backend answered — local ComfyUI, a cloud
 * provider, or the placeholder driver used before either is configured.
 *
 * Request routes are matched on the trailing path, which keeps both call shapes
 * working: direct (`/v1/images/generations`) and proxied
 * (`/proxy/https://host/v1/images/generations`).
 */
import type { IncomingMessage, ServerResponse } from 'node:http'
import { createComfyUiDriver } from './comfyui.ts'
import type { ComfyUiCheck, DriverCapabilities, GenerationProgress } from './comfyui.ts'
import type { StudioConfig } from './config.ts'
import { colorFor, gradientPng } from './png.ts'
import type { StudioStore } from './store.ts'
import { checkWorkflow as checkGraph, type StudioWorkflow, type WorkflowCheck } from './workflow-library.ts'

/**
 * One produced file, plus whatever the provider told us about how it was made.
 *
 * A file, not an image: a video workflow returns an mp4, so the mime and the
 * asset kind travel with the bytes.
 */
interface GeneratedImage {
  /** The bytes. */
  bytes: Buffer
  /** Mime type, so the library stores the video as a video. */
  mime: string
  /** `image` / `video` / `audio` / `text`. */
  kind: string
  /** Sampler seed, when the provider reported one. */
  seed?: number
}

/** A model id clients send back. */
export interface StudioModel {
  /** Model id clients send back. */
  id: string
  /** Capability this id serves. */
  capability: 'image' | 'text'
}

/** Dependencies the gateway needs. */
export interface GatewayDeps {
  /** Resolved configuration. */
  config: StudioConfig
  /** Domain store used to persist generated bytes. */
  store: StudioStore
  /** Diagnostics sink. */
  log: (message: string) => void
  /**
   * Progress sink.
   *
   * The gateway reports; it does not know who is listening. That keeps the
   * transport (SSE today, something else later) out of the render path.
   */
  onProgress?: (event: { shotId: string; progress: GenerationProgress }) => void
  /**
   * Resolve a stored workflow by id, or the default one when the id is empty.
   *
   * Injected rather than read from disk here: the library (what the operator
   * uploaded) and the gateway (what to render) are different concerns, and the
   * gateway is also built in tests that have no library at all.
   */
  resolveWorkflow?: (id: string) => StudioWorkflow | undefined
}

/** What a backend probe found; surfaced on `/api/image-backend` for ops. */
export interface BackendStatus {
  /** Which driver answered the probe. */
  driver: StudioConfig['imageDriver']
  /** Whether the backend can serve a request right now. */
  ok: boolean
  /** Human-readable summary, Chinese, safe to show in a UI banner. */
  detail: string
  /** Raw ComfyUI probe, when that driver is active. */
  comfyui?: ComfyUiCheck
}

/** A workflow check plus whether we could actually check anything. */
export interface WorkflowVerdict extends WorkflowCheck {
  /** True when the active driver cannot run ComfyUI graphs at all. */
  offline: boolean
  /** Why, in the operator's words. */
  note: string
}

/** One rendered image as callers receive it. */
export interface RenderedImage {  /** Served URL of the stored asset. */
  url: string
  /** Asset id, so callers can reference it without parsing the URL. */
  assetId: string
  /** Take recorded for this image, when the request named a shot. */
  takeId?: string
}

/** One render request, from HTTP or from the agent tool face. */
export interface RenderRequest {
  /** Prompt text. */
  prompt: string
  /** `WxH` size string; anything unparseable falls back to 1024×1024. */
  size?: string
  /** How many images to produce. */
  count?: number
  /** Clip length in seconds, for video workflows. */
  duration?: number
  /** Shot the images belong to; when set, each image records a take. */
  shotId?: string
  /** Which stored workflow to run; empty means the default one. */
  workflowId?: string
  /**
   * 输入素材：**键是画布上的端口 id**（`first` / `last` / `ref` / `in0`…），值是素材 url。
   *
   * 键直接用端口 id（而不是另起 `firstFrame` 这种名字），是为了不再需要第二张对照表：
   * 服务端按入边填，工作流里写 `$first` / `$ref` / `$in0` 就能取到，用不到的键它自己忽略。
   * 图片和视频走同一条路——`LoadImage` 与 `LoadVideo` 都只认 ComfyUI input 目录里的文件名。
   */
  inputs?: Record<string, string>
  /**
   * 非提示词、非尺寸的取值，直接当工作流占位符的值用（裁切的 `start` / `duration`…）。
   * 加一个功能就加一个键，不必改驱动签名。
   */
  params?: Record<string, number | string>
  /**
   * 固定种子（复现某一版时带上）。省略就随机。
   *
   * 「用这一版的参数再跑一次」必须包含它：同参数 + 同种子才是复现这一版，
   * 只同参数那是「同样的提示词再抽一次」。
   */
  seed?: number
}

/** Gateway surface the HTTP layer mounts. */
export interface StudioGateway {
  /** Handle one request; false when the path is not a gateway route. */
  handle: (req: IncomingMessage, res: ServerResponse, path: string) => Promise<boolean>
  /** Models advertised through `/v1/models`. */
  models: () => StudioModel[]
  /** Probe the active image backend. */
  backend: () => Promise<BackendStatus>
  /** What the active driver can report while it works. */
  capabilities: () => DriverCapabilities
  /** Validate an uploaded workflow before it is saved. */
  checkWorkflow: (graph: Record<string, { class_type: string; inputs: Record<string, unknown> }>) => Promise<WorkflowVerdict>
  /**
   * Render images and store them, exactly as an HTTP generation would.
   *
   * The agent tool face calls this so that an Agent-driven generation and a
   * human click produce the same assets, the same takes, and the same record.
   * The job runner calls it too, and passes hooks so a render can be cancelled:
   * `hooks.onQueued` hands back the backend's own id for *this* render.
   */
  renderImage: (
    request: RenderRequest,
    hooks?: {
      onQueued?: (comfyPromptId: string) => void
      onProgress?: (progress: GenerationProgress) => void
    },
  ) => Promise<RenderedImage[]>
  /**
   * Stop one render at the backend.
   *
   * A no-op for drivers that cannot be interrupted; the job still reports
   * 「已取消」 and its result is discarded, which is the promise the operator
   * actually cares about.
   */
  abortRender: (comfyPromptId: string) => Promise<void>
}

/** Write a JSON response with permissive CORS (the canvas may be on another origin). */
function json(res: ServerResponse, status: number, payload: unknown): void {
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'access-control-allow-origin': '*',
  })
  res.end(JSON.stringify(payload))
}

/** Read a request body as UTF-8 text. */
async function readText(req: IncomingMessage): Promise<string> {
  const chunks: Buffer[] = []
  for await (const chunk of req) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)))
  return Buffer.concat(chunks).toString('utf8')
}

/** Parse a JSON object body. */
function parseJson(text: string): Record<string, unknown> {
  try {
    const value: unknown = JSON.parse(text)
    return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : {}
  } catch {
    return {}
  }
}

/** Coerce a field to a trimmed string. */
function asString(value: unknown): string {
  return typeof value === 'string' ? value.trim() : ''
}

/**
 * Accept either an asset id or an asset url and return the url form.
 *
 * 画布上的节点存的是 `/api/assets/<id>`，而外部调用方（`/v1/images/generations`）
 * 手里可能只有一个 id。两种都认，比要求某一侧改格式要省事。
 */
function asAssetUrl(value: string): string {
  if (value === '') return ''
  return value.startsWith('/api/assets/') ? value : `/api/assets/${value}`
}

/**
 * Read the input-image fields an API caller may pass.
 *
 * 键就是画布上的端口 id：`first_frame` → `first`、`last_frame` → `last`、`reference` → `ref`。
 * 画布那条路**不需要**这些字段（服务端自己按入边解析），这是给没有画布的调用方的。
 * @param body - parsed request body.
 * @returns a port-id → asset-url map, or undefined when nothing was asked for.
 */
function imageInputsOf(body: Record<string, unknown>): Record<string, string> | undefined {
  const pairs: [string, string][] = [
    ['first', asString(body.first_frame ?? body.firstFrame)],
    ['last', asString(body.last_frame ?? body.lastFrame)],
    ['ref', asString(body.reference ?? body.ref)],
  ]
  const images: Record<string, string> = {}
  for (const [name, value] of pairs) {
    if (value !== '') images[name] = asAssetUrl(value)
  }
  return Object.keys(images).length === 0 ? undefined : images
}

/** Coerce a field to a bounded positive integer. */
function asCount(value: unknown): number {
  const parsed = typeof value === 'number' ? value : Number.parseInt(String(value ?? ''), 10)
  if (!Number.isFinite(parsed)) return 1
  return Math.max(1, Math.min(8, Math.floor(parsed)))
}

/** Parse a `WxH` size, defaulting to 1024×1024. */
function asSize(value: unknown): { width: number; height: number } {
  const match = /^(\d{2,5})x(\d{2,5})$/u.exec(asString(value))
  if (match === null) return { width: 1024, height: 1024 }
  return {
    width: Math.min(2048, Math.max(256, Number.parseInt(match[1] as string, 10))),
    height: Math.min(2048, Math.max(256, Number.parseInt(match[2] as string, 10))),
  }
}

/**
 * Build the gateway over the configured driver.
 * @param deps - configuration, store, and diagnostics.
 * @returns the mountable gateway.
 */
export function createGateway(deps: GatewayDeps): StudioGateway {
  const { config, store, log } = deps
  const comfyui = createComfyUiDriver({
    baseUrl: config.comfyuiUrl,
    log,
    ...(deps.resolveWorkflow === undefined ? {} : { resolveWorkflow: deps.resolveWorkflow }),
  })
  const advertised: StudioModel[] = [
    { id: config.imageDriver === 'ark' ? config.arkModel : 'studio-image', capability: 'image' },
    { id: 'studio-text', capability: 'text' },
  ]

  const placeholder = (prompt: string, size: { width: number; height: number }): Buffer =>
    gradientPng(size.width, size.height, colorFor(prompt))

  /** Ask Volcengine Ark for one image and return its bytes. */
  const arkImage = async (prompt: string, size: { width: number; height: number }): Promise<Buffer[]> => {
    if (config.arkApiKey === '') throw new Error('导演台：未配置 ARK_API_KEY')
    const response = await fetch(`${config.arkBaseUrl}/images/generations`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: `Bearer ${config.arkApiKey}` },
      body: JSON.stringify({
        model: config.arkModel,
        prompt,
        size: `${String(size.width)}x${String(size.height)}`,
        response_format: 'b64_json',
        // Ark defaults the visible watermark ON for images, which a creator
        // surface must not inherit silently.
        watermark: false,
      }),
    })
    const payload = (await response.json().catch(() => ({}))) as {
      data?: { b64_json?: string; url?: string }[]
      error?: { message?: string }
      message?: string
    }
    if (!response.ok) throw new Error(`方舟返回 ${String(response.status)}：${payload.error?.message ?? payload.message ?? '未知错误'}`)
    const images: Buffer[] = []
    for (const item of payload.data ?? []) {
      if (typeof item.b64_json === 'string' && item.b64_json !== '') images.push(Buffer.from(item.b64_json, 'base64'))
    }
    if (images.length === 0) throw new Error('方舟未返回图像数据')
    return images
  }

  /** Who produced an image, for the take record. */
  const backendIdentity = (): { providerId: string; model: string } => {
    if (config.imageDriver === 'comfyui') return { providerId: 'comfyui-local', model: 'z-image-turbo' }
    if (config.imageDriver === 'ark') return { providerId: 'ark-jimeng', model: config.arkModel }
    return { providerId: 'stub', model: 'studio-image' }
  }

  /**
   * Turn a canvas asset url into something ComfyUI can accept.
   *
   * 画布上那张图存在素材库里，而 `LoadImage` 只认 ComfyUI input 目录里的文件名，
   * 所以中间必须有一趟「读字节 → 上传」。文件名用素材 id：内容寻址，天然去重，
   * 同一张图重复用不会在 ComfyUI 那边堆一堆副本。
   * @param url - `/api/assets/<id>`, or empty.
   * @returns the bytes plus a stable file name, or undefined when there is none.
   */
  const inputOf = (url: string): { bytes: Buffer; name: string } | undefined => {
    if (url === '') return undefined
    const id = url.split('/').filter((part) => part !== '').pop() ?? ''
    const asset = store.getAsset(id)
    // 图片与视频都收：`LoadImage` 要图，`LoadVideo` 要视频，而**上传这一步是一样的**
    // （都往 ComfyUI 的 input 目录放一个文件）。别的类型（文本）不是给工作流用的。
    if (asset === undefined || (asset.kind !== 'image' && asset.kind !== 'video')) return undefined
    const bytes = store.readAsset(id)
    if (bytes === undefined) return undefined
    const dot = asset.relPath.lastIndexOf('.')
    const ext = dot === -1 ? '.bin' : asset.relPath.slice(dot)
    return { bytes, name: `${asset.id}${ext}` }
  }

  /** 把请求里那张「端口 id → 素材 url」的表读成一包字节。读不到的键直接丢掉。 */
  const inputsOf = (assets: Record<string, string> | undefined): Record<string, { bytes: Buffer; name: string }> => {
    const ready: Record<string, { bytes: Buffer; name: string }> = {}
    for (const [name, url] of Object.entries(assets ?? {})) {
      const file = inputOf(url)
      if (file !== undefined) ready[name] = file
    }
    return ready
  }

  const generate = async (
    prompt: string,
    size: { width: number; height: number },
    count: number,
    onProgress?: (progress: GenerationProgress) => void,
    workflowId = '',
    duration?: number,
    onQueued?: (comfyPromptId: string) => void,
    inputs: Record<string, { bytes: Buffer; name: string }> = {},
    params: Record<string, number | string> = {},
    seed?: number,
  ): Promise<GeneratedImage[]> => {
    // 云端与占位驱动都只出图片，所以它们的 mime 是常量；视频只可能来自本地
    // ComfyUI 工作流，也只有那条路需要按文件名判类型。
    if (config.imageDriver === 'ark') {
      return (await arkImage(prompt, size)).map((bytes) => ({ bytes, mime: 'image/png', kind: 'image' }))
    }
    if (config.imageDriver === 'comfyui') {
      return comfyui.generate({
        prompt,
        width: size.width,
        height: size.height,
        count,
        ...(workflowId === '' ? {} : { workflowId }),
        ...(duration === undefined ? {} : { duration }),
        ...(Object.keys(inputs).length === 0 ? {} : { inputs }),
        ...(Object.keys(params).length === 0 ? {} : { params }),
        ...(seed === undefined ? {} : { seed }),
      }, onProgress, onQueued)
    }
    log(`gateway: placeholder driver answered "${prompt.slice(0, 40)}" at ${String(size.width)}x${String(size.height)}`)
    return Array.from({ length: count }, () => ({ bytes: placeholder(prompt, size), mime: 'image/png', kind: 'image' }))
  }

  /**
   * Validate an uploaded workflow against the local ComfyUI.
   * @param graph - the graph to check, API format.
   * @returns the check result.
   */
  const checkWorkflow = async (graph: Record<string, { class_type: string; inputs: Record<string, unknown> }>): Promise<WorkflowVerdict> => {
    if (config.imageDriver !== 'comfyui') {
      // 别的驱动不跑 ComfyUI 工作流，如实说明，而不是假装校验过了。
      return { classes: [], missingNodes: [], missingModels: [], suggested: {}, models: {}, candidates: [], offline: true, note: `当前驱动是 ${config.imageDriver}，不执行 ComfyUI 工作流` }
    }
    return { ...checkGraph(graph, await comfyui.objectInfo()), offline: false, note: '' }
  }

  /**
   * What the active driver can promise about progress.
   *
   * The canvas asks instead of assuming, so wiring up a provider that reports
   * nothing degrades to an ETA display rather than a broken progress bar.
   */
  const capabilities = (): DriverCapabilities => {
    if (config.imageDriver === 'comfyui') return comfyui.capabilities
    // Cloud image APIs answer with the finished image and no intermediate news.
    return { progress: 'none' }
  }

  /**
   * Record one attempt against a shot, when the caller named one.
   *
   * The existence check matters: a foreign-key violation here would surface as a
   * failed generation *after* the image was already produced, which is the worst
   * possible trade. A stale shot id costs a log line instead.
   */
  const recordTake = (input: {
    shotId: string
    status: 'succeeded' | 'failed'
    assetId?: string
    seed?: number
    latencyMs: number
    prompt: string
    size: { width: number; height: number }
    count: number
    /**
     * Which workflow produced it.
     *
     * 记下来有两个用处：**按「类型 + 工作流」分开估时**（8 步与 4 步差近一倍，
     * 混在一个中位数里对两边都错），以及以后让版本条说出「这一版是几步出的」。
     * 空字符串表示「服务端自己挑的默认那套」，那就什么都不记。
     */
    workflowId?: string
    /** 输入素材（首帧/尾帧/参考图/待剪辑的片子）的文件名，按端口 id 记。 */
    inputs?: Record<string, string>
    /** 非提示词、非尺寸的取值（裁切的 start/duration），一并记下以便重跑。 */
    params?: Record<string, number | string>
    /** 片长（秒）。**必须记**：不记的话「用这一版的参数再跑一次」会退回工作流默认的 5 秒。 */
    duration?: number
    error?: string
  }): string => {
    if (input.shotId === '') return ''
    if (store.getShot(input.shotId) === undefined) {
      log(`gateway: 忽略未知镜头 ${input.shotId}（不记录 take）`)
      return ''
    }
    const identity = backendIdentity()
    const take = store.addTake({
      shotId: input.shotId,
      providerId: identity.providerId,
      model: identity.model,
      status: input.status,
      ...(input.assetId === undefined ? {} : { assetId: input.assetId }),
      params: {
        prompt: input.prompt,
        size: `${String(input.size.width)}x${String(input.size.height)}`,
        count: input.count,
        ...(input.workflowId === undefined || input.workflowId === '' ? {} : { workflow: input.workflowId }),
        ...(input.inputs === undefined || Object.keys(input.inputs).length === 0 ? {} : { inputs: input.inputs }),
        ...(input.params === undefined || Object.keys(input.params).length === 0 ? {} : { params: input.params }),
        // 片长也记进参数里：重跑时要还原「这条几秒」，而不是回到工作流的默认值。
        ...(input.duration === undefined ? {} : { duration: input.duration }),
      },
      ...(input.seed === undefined ? {} : { seed: input.seed }),
      latencyMs: input.latencyMs,
      ...(input.error === undefined ? {} : { error: input.error }),
    })
    return take.id
  }

  /** Render, store, and record takes — the single path both entries share. */
  const renderImage = async (
    request: RenderRequest,
    hooks: {
      /** Called with the driver's own id for this render, so it can be cancelled. */
      onQueued?: (comfyPromptId: string) => void
      /** Called on every progress report, on top of the canvas broadcast. */
      onProgress?: (progress: GenerationProgress) => void
    } = {},
  ): Promise<RenderedImage[]> => {
    const prompt = request.prompt.trim()
    const size = asSize(request.size)
    const count = asCount(request.count ?? 1)
    const shotId = request.shotId?.trim() ?? ''
    // 输入图（首帧/尾帧/参考图）在这一层就从素材库里读出来：**读文件归 store**，
    // 驱动只负责把字节送进 ComfyUI 的 input 目录。读不到（素材被删、文件丢了）就当没接——
    // 工作流里那条可选支路会被剪掉；要是它本来就**必需**（图生图要参考图），
    // 驱动会拒绝并说清楚缺哪个，而不是拿一个不存在的文件名去让 ComfyUI 报错。
    const inputs = inputsOf(request.inputs)
    const params = request.params ?? {}
    const started = Date.now()
    let artifacts: GeneratedImage[]
    try {
      // Progress is reported against the shot, not the HTTP request: the canvas
      // knows which node is running, and the request may be an Agent's call with
      // no browser attached at all.
      artifacts = await generate(prompt, size, count, (progress) => {
        if (shotId !== '') deps.onProgress?.({ shotId, progress })
        hooks.onProgress?.(progress)
      }, request.workflowId ?? '', request.duration, hooks.onQueued, inputs, params, request.seed)
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      // A failed attempt is still a take — without it the version history lies by omission.
      recordTake({
        shotId,
        status: 'failed',
        latencyMs: Date.now() - started,
        prompt,
        size,
        count,
        workflowId: request.workflowId ?? '',
        ...(Object.keys(inputs).length === 0 ? {} : { inputs: Object.fromEntries(Object.entries(inputs).map(([name, file]) => [name, file.name])) }),
        ...(request.duration === undefined ? {} : { duration: request.duration }),
        error: message,
      })
      throw error
    }
    const latencyMs = Date.now() - started
    return artifacts.map((artifact) => {
      // The mime and kind come from the driver, not from here: a video workflow
      // returns an mp4, and hardcoding image/png here is what made the library
      // store a video as an image.
      const asset = store.saveAsset(artifact.bytes, artifact.mime, artifact.kind)
      const takeId = recordTake({
        shotId,
        status: 'succeeded',
        assetId: asset.id,
        ...(artifact.seed === undefined ? {} : { seed: artifact.seed }),
        latencyMs,
        prompt,
        size,
        count,
        workflowId: request.workflowId ?? '',
        // 记下「这一版是从哪张图/哪段片起的」：图生视频、图生图、剪辑的版本，
        // 光看提示词分不出来。
        ...(Object.keys(inputs).length === 0 ? {} : { inputs: Object.fromEntries(Object.entries(inputs).map(([name, file]) => [name, file.name])) }),
        ...(Object.keys(params).length === 0 ? {} : { params }),
        ...(request.duration === undefined ? {} : { duration: request.duration }),
      })
      return {
        url: `/api/assets/${asset.id}`,
        assetId: asset.id,
        ...(takeId === '' ? {} : { takeId }),
      }
    })
  }

  const respondImages = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    const body = parseJson(await readText(req))
    try {
      const images = await renderImage({
        prompt: asString(body.prompt),
        size: asString(body.size),
        count: asCount(body.n),
        // The canvas names the shot a request belongs to; other clients simply omit it.
        shotId: asString(body.shotId),
        // 画布上这个节点选了哪套工作流。空 = 默认那套。
        workflowId: asString(body.workflow),
        // 视频工作流用得到；图片工作流会忽略它（图里没有 $duration 就用不上）。
        ...(body.duration === undefined ? {} : { duration: Number(body.duration) }),
        // 图生视频/图生图的输入素材：这条路没有画布节点可解析入边，所以要显式指名
        // （素材 id 或 `/api/assets/<id>` 都认）。
        ...(imageInputsOf(body) === undefined ? {} : { inputs: imageInputsOf(body) as Record<string, string> }),
        // 剪辑参数这类任意键：`params: {start: 1, duration: 3}`。
        ...(typeof body.params === 'object' && body.params !== null && !Array.isArray(body.params)
          ? { params: body.params as Record<string, number | string> }
          : {}),
        // 固定种子（复现某一版用）。省略就随机。
        ...(typeof body.seed === 'number' ? { seed: body.seed } : {}),
      })
      const data = images.map((image) => image.takeId === undefined
        ? { url: image.url }
        : { url: image.url, takeId: image.takeId })
      json(res, 200, { created: Math.floor(Date.now() / 1000), data })
    } catch (error) {
      json(res, 502, { error: { message: error instanceof Error ? error.message : String(error) } })
    }
  }

  const respondResponses = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    const body = parseJson(await readText(req))
    log(`gateway: /responses model=${asString(body.model)}`)
    const text = '导演台占位应答：尚未接入文本模型。'
    res.writeHead(200, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache', 'access-control-allow-origin': '*' })
    res.write(`data: ${JSON.stringify({ type: 'response.output_text.delta', delta: text })}\n\n`)
    res.write(`data: ${JSON.stringify({ type: 'response.completed', response: { output_text: text, output: [] } })}\n\n`)
    res.end()
  }

  /** Probe whichever backend is configured, so a misconfiguration surfaces as a message rather than a failed render. */
  const backend = async (): Promise<BackendStatus> => {
    if (config.imageDriver === 'comfyui') {
      const check = await comfyui.selfCheck()
      const problems: string[] = []
      if (!check.reachable) problems.push(`ComfyUI 不可达（${config.comfyuiUrl}）`)
      if (check.missingNodes.length > 0) problems.push(`缺少节点：${check.missingNodes.join('、')}`)
      if (check.missingModels.length > 0) problems.push(`缺少模型：${check.missingModels.join('、')}`)
      const version = check.version === undefined ? '' : ` ${check.version}`
      return {
        driver: config.imageDriver,
        ok: problems.length === 0,
        detail: problems.length > 0 ? problems.join('；') : `本地 ComfyUI${version} 就绪`,
        comfyui: check,
      }
    }
    if (config.imageDriver === 'ark') {
      return {
        driver: config.imageDriver,
        ok: config.arkApiKey !== '',
        detail: config.arkApiKey === '' ? '未配置 ARK_API_KEY' : `火山方舟 ${config.arkModel}`,
      }
    }
    return { driver: config.imageDriver, ok: true, detail: '占位驱动（返回真实尺寸渐变图）' }
  }

  return {
    models: () => advertised,
    backend,
    capabilities,
    checkWorkflow,
    renderImage,
    async abortRender(comfyPromptId) {
      // 只有本地 ComfyUI 能真的被中止；云端 API 一旦提交就只能等它回来，
      // 那时作业照样标记为已取消、结果丢掉——这是对使用者的承诺。
      if (config.imageDriver !== 'comfyui') return
      await comfyui.abort(comfyPromptId)
    },
    async handle(req, res, path) {
      if (req.method === 'OPTIONS') {
        res.writeHead(204, { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'GET,POST,OPTIONS' })
        res.end()
        return true
      }
      if (path.endsWith('/models')) {
        json(res, 200, { data: advertised.map((model) => ({ id: model.id })) })
        return true
      }
      if (path.endsWith('/images/generations') || path.endsWith('/images/edits')) {
        await respondImages(req, res)
        return true
      }
      if (path.endsWith('/responses')) {
        await respondResponses(req, res)
        return true
      }
      return false
    },
  }
}
